version: '3'

volumes:
  frontend_node_modules:
  backend_node_modules:

services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./frontend:/workdir
      - frontend_node_modules:/workdir/node_modules
    command: /bin/bash -c "npm install && exec npm run concurrent"

  backend:
    build: backend
    container_name: backend
    depends_on:
      - db
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - ./backend:/workdir
      - backend_node_modules:/workdir/node_modules
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test?schema=public
    command: /bin/bash -c "npm install && npx prisma db push --preview-feature && npx prisma generate && npx prisma db seed && (npx prisma studio &) && exec npm run start:dev"

  db:
    build: db
    container_name: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test
    restart: always

