version: "3"

volumes:
  frontend_node_modules:
  backend_node_modules:

services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 3000:3000
      - 6006:6006
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/workdir
      - frontend_node_modules:/workdir/node_modules
    command: ["bash", "docker-entrypoint.sh"]

  backend:
    build: backend
    container_name: backend
    depends_on:
      - db
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - ./backend:/workdir
      - backend_node_modules:/workdir/node_modules
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/test?schema=public
    command: ["bash", "docker-entrypoint.sh"]

  db:
    build: db
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    restart: always
