# This is a github action to check if the code style is correct.

name: check-code-style
on: [pull_request, workflow_dispatch]
jobs:
  make-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: cache frontend node-modules
        id: cache-frontend-node-modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: cache-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: cache backend node-modules
        id: cache-backend-node-modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: cache-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}

      - name: frontend fmt-ck
        run: cd frontend && npm install && make fmt-ck
      - name: backend fmt-ck
        run: cd backend && npm install && make fmt-ck
