# This is a github action to check for errors in linter.

name: check-lint
on: [pull_request, workflow_dispatch]
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
      - name: npm install
        run: cd backend && npm install
      - name: backend make lint
        run: timeout 300 make -C backend lint
