# This is a github action to check if the code style is correct.

name: check-code-style

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  make-fmt:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: cache frontend node-modules
        id: cache-frontend-node-modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: cache-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: cache backend node-modules
        id: cache-backend-node-modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: cache-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}

      - name: frontend npm install
        run: cd frontend && npm install
      - name: frontend fmt-ck
        run: cd frontend && timeout 300 make fmt-ck

      - name: backend npm install
        run: cd backend && npm install
      - name: backend fmt-ck
        run: cd backend && timeout 300 make fmt-ck
      - name: backend prisma fmt ck
        run: cd backend && timeout 300 make fmt && (! git status -s | grep 'prisma') 
