# This is a github action to check for errors in linter.

name: check-lint
on: [pull_request, workflow_dispatch]
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: frontend
        run: cd frontend && npm install
      - name: backend
        run: cd backend  && npm install
