name: cat file
on: [pull_request, workflow_dispatch]

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
      - name: show file
        run: exit 1
