# storybook test

name: storybook-test
on: [pull_request, workflow_dispatch]
jobs:
  storybook-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: cache frontend node-modules
        id: cache-frontend-node-modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: cache-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: frontend npm install
        run: cd frontend && npm install
      - name: install playwright
        run: cd frontend && npx playwright install && npx playwright install-deps
      - name: run storybook test
        run: cd frontend && npm run storybook-test-ci
