# storybook test

# ref
# - https://github.com/microsoft/playwright-github-action
# - `~/.cache/ms-playwright`
#   - https://playwright.dev/docs/ci

name: storybook-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DATABASE_URL: postgresql://test:test@localhost:5432/test?schema=public

jobs:
  storybook-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: install playwright
        run: cd frontend && npx playwright install
      - name: npx playwright install-deps
        run: npx playwright install-deps
